version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - inditex_network
    restart: always

  test-runner:
    image: maven:3.9.6-eclipse-temurin-21
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/inditex_test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_PROFILES_ACTIVE: test
    command: mvn test -e
    networks:
      - inditex_network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: inditex             
      MYSQL_PASSWORD: root                   
      MYSQL_ROOT_PASSWORD: root              
    ports:
      - "3306:3306"                          
    networks:
      - inditex_network
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d

networks:
  inditex_network:
    driver: bridge